# Generated by Django 2.1.1 on 2018-09-26 20:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='createt',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='list',
            name='due',
            field=models.DateField(blank=True, null=True, verbose_name='Date'),
        ),
    ]
