# Generated by Django 2.1.1 on 2018-10-06 05:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('create', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('text', models.CharField(max_length=800)),
            ],
        ),
    ]
