# Generated by Django 2.1.1 on 2018-09-26 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180927_0235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='createt',
            new_name='create',
        ),
    ]
