# Generated by Django 2.1.1 on 2018-10-12 13:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(max_length=2)),
                ('comment', models.TextField()),
                ('date', models.DateField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
