# Generated by Django 2.1.1 on 2018-10-12 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0002_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='name',
            new_name='named',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='name',
            new_name='namer',
        ),
    ]
